ACCOUNT_BALANCE_FIELD_PATHS = {
    "account_id": ["account", "accountId"],
    "account_display_id": ["account", "accountDisplayId"],
    "currency": ["account", "currency"],
    "client_id": ["account", "clientId"],
    "account_type__key": ["account", "accountType", "key"],
    "account_type__text": ["account", "accountType", "text"],
    "iban": ["account", "iban"],
    "bic": ["account", "bic"],
    "credit_limit__value": ["account", "creditLimit", "value"],
    "credit_limit__unit": ["account", "creditLimit", "unit"],
    "balance__value": ["balance", "value"],
    "balance__unit": ["balance", "unit"],
    "balance_eur__value": ["balanceEUR", "value"],
    "balance_eur__unit": ["balanceEUR", "unit"],
    "available_cash_amount__value": ["availableCashAmount", "value"],
    "available_cash_amount__unit": ["availableCashAmount", "unit"],
    "available_cash_amount_eur__value": ["availableCashAmountEUR", "value"],
    "available_cash_amount_eur__unit": ["availableCashAmountEUR", "unit"],
}

ACCOUNT_TRANSACTION_FIELD_PATHS = {
    "reference": ["reference"],
    "booking_status": ["bookingStatus"],
    "booking_date": ["bookingDate"],
    "amount__value": ["amount", "value"],
    "amount__unit": ["amount", "unit"],
    "remitter__holder_name": ["remitter", "holderName"],
    "deptor": ["deptor"],
    "creditor": ["creditor"],
    "creditor__holder_name": ["creditor", "holderName"],
    "creditor__iban": ["creditor", "iban"],
    "creditor__bic": ["creditor", "bic"],
    "valuta_date": ["valutaDate"],
    "direct_debit_creditor_id": ["directDebitCreditorId"],
    "direct_debit_mandate_id": ["directDebitMandateId"],
    "end_to_end_reference": ["endToEndReference"],
    "new_transaction": ["newTransaction"],
    "remittance_info": ["remittanceInfo"],
    "transaction_type__key": ["transactionType", "key"],
    "transaction_type__text": ["transactionType", "text"],
}
