name: Build and Push Airflow Docker Image

on:
  push:
    tags:
      - "airflow*"
  pull_request:
    branches:
      - main
    paths:
      - "src/plumbing_core/**"
      - "src/plumbing_airflow/pyproject.toml"
      - "src/plumbing_airflow/Dockerfile"
      - "src/plumbing_airflow/dags/**"

env:
  REGISTRY: ghcr.io
  AIRFLOW_IMAGE_NAME: ${{ github.repository_owner }}/plumbing-airflow

jobs:
  build-and-push-airflow:
    name: Build and Push Airflow
    runs-on: ubuntu-latest
    # Run for airflow tags OR pull requests
    if: contains(github.ref, 'airflow') || github.event_name == 'pull_request'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Generate requirements.txt
        run: |
          cd src/plumbing_airflow
          uv pip compile pyproject.toml -o requirements.txt

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag or branch name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "IS_PR=true" >> $GITHUB_OUTPUT
          else
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "IS_PR=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/plumbing_airflow/Dockerfile
          push: true
          # linux/amd64 would also be the default as a linux runner is building the image. This is just to be explicit.
          platforms: linux/amd64
          build-args: |
            CI_COMMIT_HASH=${{ github.sha }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.AIRFLOW_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ steps.tag.outputs.IS_PR == 'false' && format('{0}/{1}:latest', env.REGISTRY, env.AIRFLOW_IMAGE_NAME) || '' }}

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      is_pr: ${{ steps.tag.outputs.IS_PR }}
      app: airflow
