name: Build and Push Airflow Docker Image

on:
  push:
    tags:
      - "plumbing-airflow-v*"

env:
  REGISTRY: ghcr.io
  AIRFLOW_IMAGE_NAME: ${{ github.repository_owner }}/plumbing-airflow

jobs:
  build-and-push-airflow:
    name: Build and Push Airflow
    runs-on: ubuntu-latest
    # Run only for plumbing-airflow release tags
    if: startsWith(github.ref, 'refs/tags/plumbing-airflow-v')

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Generate requirements.txt
        run: |
          cd src/plumbing_airflow
          uv pip compile pyproject.toml -o requirements.txt

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/plumbing-airflow-}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/plumbing_airflow/Dockerfile
          push: true
          # linux/amd64 would also be the default as a linux runner is building the image. This is just to be explicit.
          platforms: linux/amd64
          build-args: |
            CI_COMMIT_HASH=${{ github.sha }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.AIRFLOW_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ env.AIRFLOW_IMAGE_NAME }}:latest

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      app: airflow
