name: Release Please

on:
  push:
    branches:
      - main
    paths:
      - "src/plumbing_airflow/dags/**"
      - "src/plumbing_airflow/plugins/**"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Will not trigger other workflow when using GITHUB_TOKEN
          # token: ${{ secrets.GITHUB_TOKEN }}
          token: "${{ secrets.PLUMBING_TOKEN }}"
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
